### ISSUE TITLE
The payment method supplied does not belong to a Customer, but you supplied Customer XYZ. Please attach the payment method to this Customer before using it with a SetupIntent.

### ISSUE THREAD

**Issue by phillmorgan28** [laravel/cashier#720] opened 2019-07-29 20:31 UTC
- Cashier Version: 10 beta
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:
I have created a brand new customer using createOrGetStripeCustomer() and ensured that my logged in user matches the created Stripe user. I then created a new setup intent using $user->createSetupIntent(). I passed the secret to the JS on the client side and I am attempting to create a payment method without creating a subscription using elements. The error I am receiving is:

The payment method supplied (pm_1234567890) does not belong to a Customer, but you supplied Customer cus_1234567890. Please attach the payment method to this Customer before using it with a SetupIntent.

It looks like the payment method is created, but since the SetupIntent already has a customer ID assigned, it is failing because I've not attached the method to the customer yet. The current docs (although a WIP) seem to suggest that I don't need to attach it manually as this is the purpose of a SetupIntent. It seems strange that we can create a setup intent with a customer already assigned, but we can't create a payment method with it. I am obviously missing something. Anyone have any ideas?

**Comment by phillmorgan28** [comment] 2019-07-29 21:22
As an update to this, if I manually create the setup intent without the customer ID and perform the same sequence, the payment method is created and can be assigned in server side code using $user->addPaymentMethod() and updateDefaultPaymentMethod()

**Comment by driesvints** [comment] 2019-07-30 13:25
Heya, we actually encountered this ourselves two weeks ago and it's already been fixed on master. Will tag a new beta2 version soon! Thanks for reporting!

**Closed by driesvints** 2019-07-30 13:25 UTC

**Comment by precompiled** [comment] 2020-03-29 09:20
Hey @driesvints, I can see this is a reason for #704 (and also referring #745)

I have similar flow as OP described, and I've tried passing `['customer' => $user->stripe_id]` to `createSetupIntent()` to reproduce the error, but cannot. Maybe I'm missing something?

Since the `createSetupIntent()` method is invoked on a **user**, one would expect a SetupIntent to be tied to that particular user (Stripe customer).

Following official documentation, that seems to be default and expected behaviour. https://laravel.com/docs/6.x/billing#storing-payment-methods

> When storing credit cards to a **customer** for future use, the Stripe Setup Intents API must be used to securely gather the customer's payment method details. A "Setup Intent" indicates to Stripe the intention to charge a **customer's** payment method.

At no point is developer suggested to pass `['customer' => $user->stripe_id]` as a method argument.

There are various flows where attaching a customer to the `SetupIntent` would produce valid result. For example -when creating new subscription or [adding a new card ](https://stripe.com/docs/payments/save-and-reuse#web-collect-card-details) (this one would fail if no customer is attached to SetupIntent, and is the reason why I investigated and posted here).

I believe this needs either better explanation in the official docs or a way to distinct the **customer** parameter (i.e. a boolean parameter) from other associative array data passed.

Thanks!

**Comment by driesvints** [comment] 2020-03-30 09:01
@precompiled since we haven't had any issues with people not being able to attach cards without the customer parameter I don't see any reason to adjust anything, sorry. The `createSetupIntent` method has an `$options` parameter where you can pass that in if you want to.
