### ISSUE TITLE
Plans Discontinued

### ISSUE THREAD

**Issue by Stoyvo** [laravel/cashier#967] opened 2020-07-01 23:29 UTC
- Cashier Version: 12.2.0
- Laravel Version: 7.0

### Description:
Stripe has discontinued Plans. They now use Price API. Price API is backwards compatible, however Cashier documentation and default functionality is very difficult to follow when both systems have different terminology and API expectations.

### Steps To Reproduce:
https://stripe.com/docs/api/plans

**Comment by driesvints** [comment] 2020-07-02 09:01
Duplicate of https://github.com/laravel/cashier/issues/956

**Closed by driesvints** 2020-07-02 09:01 UTC
