### ISSUE TITLE
Open for  extension for anothers payment gateways

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/cashier#506] opened 2018-04-16 17:08 UTC
How I can extends the package? The package no has interface for extenson for anothers payment gatesys. I would like extend the package for payment gateway of my country.

**Comment by IgorDePaula** [comment] 2018-04-26 13:38
Hello?

**Comment by driesvints** [comment] 2018-10-08 15:30
Duplicate of https://github.com/laravel/cashier/issues/395

**Closed by driesvints** 2018-10-08 15:30 UTC
